brbid_backend_challenge/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, re_path

from main import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login', auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('register', views.register, name='register'),
    re_path('s/(?P<short_id>[0-9a-zA-Z]*)', views.home, name='home'),
    path('admin/', admin.site.urls),
    #re_path('(?P<short_id>[0-9a-zA-Z]*)', views.home, name='home'), # TODO: Usar algo similar
]

main/models.py
import time
from urllib.parse import urlparse

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


#
# TODO: Talvez https://pypi.org/project/django-hashid-field/ fosse uma solução
# mais limpa para implmentar o id. Considerar no futuro
#


class ShortURL(models.Model):
    # Tamanho máximo aceitavel de acordo com: https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers/417184#417184
    original = models.URLField(max_length=2000)
    shortened_id = models.BigIntegerField()
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    # FIXME: Talvez sobreescrever save fosse uma melhor solução
    @classmethod
    def create(cls, original):
        """
            Cria um objeto ShortURL e inicializa seu id com o timestamp atual
            Se isso fosse uma aplicação real talvez um valor aleatório (~salt~) pudesse ser somado ao timestamp para evitar chance de colisão
        """
        short_url = cls(original=original)
        short_url.shortened_id = int(time.time())
        return short_url

    def get_shortened_url(self):
        """
            Monta a URL curta codificando o id em hexadecimal
        """
        return '{}://{}/s/{}'.format(
            'http',
            settings.BASE_URL,
            hex(self.shortened_id)[2:]
        )

    @classmethod
    def find_by_short_id(cls, hex_id):
        """
            Para uma string, tenta converter em hexadecimal e obter um ShortURL com esse identificador
        """
        
        url_id = int('0x' + hex_id, 16)

        return cls.objects.get(shortened_id=url_id)

main/forms.py
from django.forms import modelform_factory, TextInput

from .models import ShortURL


ShortURLForm = modelform_factory(ShortURL, fields=("original",),
    labels={
        "original": ""
    },
    widgets={
    "original": TextInput()
})

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm

from .forms import ShortURLForm
from .models import ShortURL

def home(request, short_id=None):

    short_url = ''

    if request.method == 'POST':
        form = ShortURLForm(request.POST)
        if form.is_valid():
            # FIXME: Para evitar refatorar o model ShortURL
            instance = form.instance.create(form.instance.original)
            if request.user.is_authenticated:
                instance.user = request.user
            instance.save()
            short_url = instance.get_shortened_url()
    else:
        if request.method == 'GET' and short_id != None:
            original_url = ShortURL.find_by_short_id(short_id).original
            return HttpResponseRedirect(original_url)
        else:
            form = ShortURLForm()

    context = {
        'message': 'Cole a sua URL abaixo',
        'form': form,
        'short_url': short_url
    }
    return render(request, 'main/index.html', context)


def register(request):
    if request.method == 'POST':
        f = UserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'Conta criada com sucesso')
            return redirect('home')

    else:
        f = UserCreationForm()

    return render(request, 'main/register.html', {'form': f})

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <title>{% block title %}Encurtador de URLs{% endblock %}</title>
        <style>
            body {
                display: block;
                background: url({% static "blank-business-composition-373076.jpg" %});
                background-size: cover;
                background-repeat: no-repeat;
            }
            #menu {
                background: lightgray;
                padding: 14px 10px 0 0;
                border-radius: 6px;
                margin: 10px;
                border: solid 1px lightslategray;
                height: 2em;
                text-align: right;
            }
            #center_box {
                margin: 5% 25%;
                display: block;
                background: darkgray;
                padding: 30px 20px;
                border: solid 1px gray;
                border-radius: 5px;
                font-size: larger;
            }
            #center_box p {
                margin: 0px 0 20px 0
            }
            #url_curta {
                border: solid 1px;
                border-radius: 3px;
                padding: 0 0px 0 10px;
                margin: 10px 0;
                background: lightgray;
                height: 3em;
            }
            #url_curta a {
                margin-top: 1em;
                display: inline-block;
            }
            #copy_button {
                float: right;
                right: 0;
            }
            #menu a {
                border: solid 1px black;
                border-radius: 3px;
                padding: 8px;
                background: white;
                text-decoration: none;
                margin-right: .5em;
                color: black;
                text-shadow: lightgrey 1px 1px;
            }
            #menu em {
                float: left;
                margin-left: 20px;
            }
            #id_original {
                font-size: inherit;
                width: 80%;
                height: 3em;
                border: 0;
                padding: 0 10px;
            }
            input[type="button"], input[type="submit"] {
                padding: 0 15px;
                position: relative;
                height: 3em;
                border: 0;
                background: #1d2027;
                color: white;
                top: 0;
                right: 10px;
                font-size: inherit;
            }
            #short_url_list {
                margin: auto;
                width: 60%;
            }
        </style>
    </head>
    <body>
        <div id="menu">
            {% block menu %}Menu{% endblock %}
        </div>
        <div id="center_box">
            {% block content %}Conteúdo{% endblock %}
        </div>
        {% block user_links %}{% endblock %}
        {% block script %}{% endblock %}
    </body>
</html>

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block menu %}
    {% if user.is_authenticated %}
            <em>Olá, {{ user.username }}</em>
            <a href="/logout">Sair</a>
    {% else %}
            <a href="/register">Cadastro</a>
            <a href="/login">Login</a>
    {% endif %}
{% endblock %}

{% block content %}
    {% if messages %}
            <ul>
        {% for message in messages %}
                <li>{{ message }}</li>
        {% endfor %}
            </ul>
    {% endif %}

            <p>{{ message }}</p>
            <form action="/" method="post">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Encurte">
            </form>
    {% if short_url != '' %}
            <div id="url_curta">
                <a id="short_url" href="{{ short_url }}">{{ short_url }}</a><input id="copy_button" type="button" value="Copy" />
            </div>
    {% endif %}
{% endblock %}

{% block user_links %}
    {% if user.shorturl_set.count > 0 %}
        <div id="short_url_list">
            <h1>Seus links curtos</h1>
            <table>
        {% for su in user.shorturl_set.all %}
                <tr>
                    <td><a href="{{ su.get_shortened_url }}">{{ su.get_shortened_url }}</a></td>
                    <td>{{ su.original }}</td>
                </th>
        {% endfor %}
            </table>
        </div>
    {% endif %}
{% endblock %}

{% block script %}
    <script src="{% static "copy.js" %}"></script>
    <script>
        var copy_button = document.getElementById("copy_button");
        var short_url = document.getElementById("short_url");
        if(short_url != null) {
            addCopyToClipboard(copy_button, short_url);
        }
    </script>
{% endblock %}

main/templates/main/login.html
{% extends "main/base.html" %}

{% block title %}Login{% endblock %}

{% block menu %}{% endblock %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{#% url 'password_reset' %#}">Lost password?</a></p>

{% endblock %}

main/templates/main/register.html
{% extends "main/base.html" %}

{% block title %}Cadastro{% endblock %}

{% block menu %}{% endblock %}

{% block content %}
     <div class="login">

         {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <h1>Criação de conta</h1>

         <form method="post" >
             {% csrf_token %}
             <table>
                {{ form.as_table }}
                 <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Cadastrar" /></td>
                </tr>
             </table>
         </form>
     </div>
{% endblock %}